// SPDX-License-Identifier: Apache-2.0
// aes128.hpp - a minimal, from-scratch AES-128 (FIPS 197) FORWARD (encrypt) cipher, single block
// only. Exists for exactly one reason: RFC 9001's QUIC Initial-packet protection uses
// AEAD_AES_128_GCM unconditionally (regardless of whatever cipher suite the handshake itself
// eventually negotiates -- see RFC 9001 section 5.2), and GCM's own confidentiality mode is CTR
// (counter) mode -- which, unlike CBC or other block-chaining modes, uses the block cipher's
// ENCRYPT direction for both encryption and decryption (the keystream is generated by encrypting
// successive counter values, then XORed with the ciphertext either way). RFC 9001's own header
// protection mask (section 5.4) is likewise always a single AES-ECB *encrypt* of a 16-byte sample.
// So this codebase never needs AES decrypt (InvSubBytes/InvShiftRows/InvMixColumns) at all -- see
// aes128_gcm.hpp for the GCM layer built on top of this, and quic.hpp for the one caller.
#pragma once

#include <cstdint>

namespace conduitscope {

// Encrypts exactly one 16-byte block `in` under 16-byte key `key`, per FIPS 197 (Nk=4, Nr=10).
void aes128_encrypt_block(const uint8_t key[16], const uint8_t in[16], uint8_t out[16]);

}  // namespace conduitscope
