// SPDX-License-Identifier: MIT
// mms.hpp - IEC 61850 MMS (Manufacturing Message Specification, ISO 9506) decoding.
//
// MMS always rides inside a COTP Data (DT) frame's user data (see cotp.hpp) on TCP port 102 --
// the SAME transport and port S7comm uses (see s7comm.hpp) -- but MMS is not S7comm: it is a
// full, independent ISO/OSI application built on THREE more layers stacked on top of COTP,
// each with its own ASN.1 BER (Basic Encoding Rules) TLV encoding:
//
//   COTP Data frame user data
//     -> ISO 8327-1 Session Protocol       (one SPDU: type + length + optional parameters)
//       -> ISO 8823 Presentation Protocol  (CP-type/CPA-type at association time, or a bare
//                                            "fully-encoded-data" wrapper on every later message)
//         -> ISO 8650-1 ACSE               (AARQ/AARE/RLRQ/RLRE/ABRT -- association-time only)
//           -> MMS (ISO 9506)              (the actual application PDU -- Initiate, Read, Write,
//                                            GetNameList, Report, ... -- this is what this whole
//                                            decoder exists to reach)
//
// This decoder walks all four layers to reach the MMS PDU, decoding enough of Session/
// Presentation/ACSE to (a) correctly locate the next layer's bytes and (b) surface genuinely
// useful association-time detail (which abstract syntaxes/application-context were negotiated,
// whether the association was accepted), then gives the MMS PDU itself -- the actual
// read/write/report traffic an OT security review cares about -- the deepest decode in this
// file, including, unlike this codebase's own OPC UA decoder's Variant/DataValue gap, MMS's
// own "Data" value type (see "The Data value type" below): this codebase does NOT leave MMS's
// actual read/write VALUES undecoded.
//
// Sourcing: every field and tag number below is cross-checked against the actual ASN.1 module
// text for each layer -- ISO 8327-1's own SPDU type/parameter codes (this decoder's own
// reference for those is the Wireshark project's packet-ses.h, which tabulates every SPDU type
// and parameter code exactly as ISO 8327-1's own tables define them), ISO 8823's CP-type/
// User-data grammar and ISO 8650-1's ACSE-apdu grammar (both cross-checked against the
// Wireshark project's own asn2wrs-generated packet-pres.c/packet-acse.c, which are themselves
// compiled directly from those two layers' ASN.1 modules, not hand-transcribed), and MMS's own
// ISO 9506-2 ASN.1 module (this decoder's primary source is the actual `mms.asn` module
// Wireshark's own asn2wrs compiler consumes to generate packet-mms.c -- i.e. the same
// "generated from the standard's own machine-readable grammar, so it can't disagree with real
// interop without breaking it" sourcing standard this codebase already applies to OPC UA's
// NodeIds.csv/StatusCode.csv). Every tag number this file asserts was ADDITIONALLY confirmed
// byte-for-byte, by hand, against real captured traffic cross-checked with `tshark -V`/`-x`
// (both this decoder's own synthetic fixture traffic generated by building and running the
// independent, widely-used open-source `libiec61850` stack's own client/server example programs
// in this project's own development environment, and genuine real-world captures -- see
// tests/real_captures/mms/ATTRIBUTION.md for the full detail on both).
//
// ---------------------------------------------------------------------------------------------
// ASN.1 BER TLV basics (used by all four layers below except Session, which uses its own
// simpler PGI/PI TLV scheme -- see "Session layer" below): every value is Tag(1 byte, for every
// tag this file needs -- none exceeds the 5-bit short form) + Length(1 byte short form for
// lengths < 128, or 0x80|N followed by N big-endian length bytes for the long form) + that many
// content bytes. A tag byte's top 2 bits are its class (00 UNIVERSAL, 01 APPLICATION, 10
// CONTEXT-specific, 11 PRIVATE), bit 0x20 marks it constructed (contains nested TLVs) vs.
// primitive (raw value bytes), and the low 5 bits are the tag number. This decoder implements
// its own small, private BER TLV reader (mms.cpp, unexported) rather than pulling in a general
// ASN.1 library, the same "hand-roll the specific subset actually needed" posture this codebase
// already takes for GOOSE/SV's own BER-encoded IEC 61850 payloads.
//
// ---------------------------------------------------------------------------------------------
// Session layer (ISO 8327-1): one SPDU = SI(1 byte, the SPDU type) + LI(1 byte -- unlike BER,
// this is a PLAIN length, 0-254; 255 is reserved to mean "2-byte extended length follows", never
// observed in this decoder's own research and not implemented) + LI bytes of parameters.
// Session parameters use their own nested TLV scheme, NOT ASN.1 BER: a Parameter Group
// Indicator (PGI, one byte, values >= 1 whose own content is itself a nested list of
// PI/PGI-coded parameters) or a plain Parameter Indicator (PI, one byte) is followed by a
// 1-byte length and that many content bytes. This decoder walks that list generically for
// every SPDU type that carries parameters (CONNECT/ACCEPT/REFUSE/FINISH/DISCONNECT/ABORT alike
// -- the parameter-list encoding itself does not depend on which SPDU type it is inside), and
// specifically extracts PGI 193 ("Session user data") or 194 ("Extended user data") when
// present -- that parameter's own content IS the next layer's (Presentation's) bytes.
//
// The SPDU type codes this decoder recognizes by name (every value ISO 8327-1 and this
// decoder's own real-capture research actually found in IEC 61850 MMS traffic): CONNECT (CN,
// 13), ACCEPT (AC, 14), REFUSE (RF, 12), FINISH (FN, 9), DISCONNECT (DN, 10), ABORT (AB, 25),
// ABORT ACCEPT (AA, 26), and DATA TRANSFER / GIVE TOKENS (both share SPDU type 1 on the wire --
// see "The ubiquitous SI=1 case" below). Any other SPDU type is still structurally recognized
// (SI/LI consumed correctly so byte alignment for whatever follows stays correct) but shown
// only by its raw type number, not decoded further -- this first-pass release's own research
// (both the independent-stack traffic and the real captures in ATTRIBUTION.md) found real IEC
// 61850 MMS traffic uses only the SPDU types named above.
//
// The ubiquitous SI=1 case: ISO 8327-1 assigns SPDU type 1 to BOTH "Give Tokens" and "Data
// Transfer" (they are genuinely the same numeric SPDU type; which one an implementation "means"
// is a matter of session-layer token-passing context this decoder does not track -- see
// "Deliberately NOT implemented" below). In every real and independent-stack-generated capture
// this decoder's own research examined, an ordinary ongoing MMS message (everything after the
// initial association is established) is preceded by one or more back-to-back SI=1/LI=0
// (parameter-free) SPDUs -- commonly exactly two, "Give Tokens" then "Data Transfer" -- with no
// parameters at all, meaning the Presentation-layer bytes begin immediately after them. This
// decoder consumes any number (one or more) of consecutive SI=1/LI=0 pairs generically rather
// than hard-coding "exactly two" or trying to distinguish "Give Tokens" from "Data Transfer"
// semantically (both cases behave identically for this decoder's own purposes: skip the
// SI=1/LI=0 marker(s), the Presentation layer starts right after) -- this decoder labels this
// shape "DATA TRANSFER / GIVE TOKENS" rather than confidently picking one name.
//
// Bare MMS (no Session/Presentation/ACSE at all): this decoder's own real-capture research (see
// ATTRIBUTION.md) found genuine historical MMS traffic that skips the Session/Presentation/ACSE
// layers ENTIRELY -- the COTP Data frame's user data begins directly with an MMS PDU's own tag
// byte (0xA0-0xAD, see "MMS layer" below). Since every valid Session SPDU type this decoder
// recognizes is a small number (1-26) and every MMS top-level PDU tag is CONTEXT-class
// constructed with the class+constructed bits set (0xA0 and above), there is no ambiguity: this
// decoder checks the leading byte against the Session SPDU shape first, and falls back to
// trying the bytes as a bare MMS PDU only when that check fails -- see "Structural detection
// gate" below for exactly how this fallback is bounded so it cannot mis-fire on non-MMS COTP
// traffic (S7comm is always tried first regardless -- see s7comm.hpp -- so this fallback is only
// ever reached once S7comm's own, stronger, single-byte protocol-id gate has already failed).
//
// ---------------------------------------------------------------------------------------------
// Presentation layer (ISO 8823): at association time (inside a Session CONNECT/ACCEPT SPDU's
// own user-data parameter), this is a CP-type (request) or CPA-type (accept) SET containing,
// among other optional fields this decoder does not surface individually, a
// presentation-context-definition-list -- a SEQUENCE OF {presentation-context-identifier
// INTEGER, abstract-syntax-name OBJECT IDENTIFIER, transfer-syntax-name-list} entries. This
// decoder decodes this list into a small number of "context N = <name> (<OID>)" values (e.g.
// "context 1 = ACSE (2.2.1.0.1)", "context 3 = MMS (1.0.9506.2.1)") -- itself a useful
// association-time detail -- and then, like every SPDU, unwraps the SET's own "user-data"
// CHOICE field: this decoder only implements the "fully-encoded-data" alternative (APPLICATION
// class, constructed, tag 1 -- i.e. leading byte 0x61), a SEQUENCE OF PDV-list, each PDV-list
// being {presentation-context-identifier INTEGER, presentation-data-values CHOICE}. This
// decoder only implements the "single-ASN1-type" alternative of that CHOICE (CONTEXT tag 0,
// i.e. leading byte 0xA0) -- the one alternative this decoder's own research (spec text and
// every capture examined, real and independent-stack-generated alike) ever found in practice --
// whose own content is that PDV's actual payload: ACSE (when presentation-context-identifier
// resolves to the ACSE context) or MMS directly (when it resolves to the MMS context). The
// "simply-encoded-data" (APPLICATION 0) alternative is recognized as a distinct, valid shape
// but not decoded further (shown as raw hex) -- no real capture using it was found.
//
// Resolving which context-id means ACSE vs. MMS: this decoder is, like every other protocol in
// this codebase, a STATELESS per-message decoder (see "Deliberately NOT implemented" below) --
// it cannot remember a context-definition-list negotiated in an EARLIER Connect frame while
// decoding a LATER ongoing Data-Transfer frame that references a context-id by number alone. In
// every capture this decoder's own research examined (both independent-stack-generated and
// real-world), the negotiated numbering is IDENTICAL: context-id 1 = ACSE, context-id 3 = MMS
// -- this is not a coincidence unique to one implementation; it is the de-facto universal
// convention essentially every IEC 61850 MMS stack uses. This decoder assumes that convention
// for any Data-Transfer-layer PDV whose own frame has no in-message context-definition-list to
// resolve it against (i.e. every ongoing message, once association is established) -- an
// honestly-stated convention, not a guess invented for this decoder, and consistent with the
// same "verify against real, independent traffic" discipline this codebase applies everywhere.
//
// ---------------------------------------------------------------------------------------------
// ACSE layer (ISO 8650-1 / X.227): present only inside an association's own CP-type/CPA-type
// user-data (i.e. only on the frame(s) that establish or release an association), never on an
// ongoing Data-Transfer message (those carry MMS directly at presentation-context 3). This
// decoder recognizes all five top-level ACSE APDU tags -- AARQ (APPLICATION 0, 0x60), AARE
// (APPLICATION 1, 0x61 -- note this is the SAME byte value as Presentation's own
// "fully-encoded-data" wrapper tag; there is no real ambiguity because this decoder always
// dispatches on ACSE tags only AFTER already having separately consumed and unwrapped the
// Presentation layer's own single-ASN1-type content, a purely POSITIONAL disambiguation, not a
// byte-value one), RLRQ (APPLICATION 2, 0x62), RLRE (APPLICATION 3, 0x63), ABRT (APPLICATION 4,
// 0x64) -- and decodes, from whichever is present: the application-context-name (an OBJECT
// IDENTIFIER -- for MMS/IEC 61850 traffic this is always 1.0.9506.2.3, shown alongside its name
// when recognized), AARE's own result (accepted/rejected-permanent/rejected-transient) and
// result-source-diagnostic, and -- the field this decoder actually needs to reach MMS --
// user-information (CONTEXT tag 30, 0xBE): a SEQUENCE OF EXTERNAL whose first (and, in every
// capture this decoder's own research found, only) entry's own "encoding" CHOICE field, when it
// is single-ASN1-type (CONTEXT tag 0, 0xA0 -- the only alternative this decoder implements, the
// only one ever observed), contains the MMS PDU this whole exercise exists to reach --
// Initiate-RequestPDU inside an AARQ's own user-information, Initiate-ResponsePDU inside an
// AARE's own. AARQ/AARE's calling/called-AP-title and AE-qualifier fields (when present) are
// each EXPLICITLY tagged (an outer CONTEXT-class constructed tag wrapping the alternative's own
// natural, fully-tagged encoding -- e.g. AP-title-form2's own UNIVERSAL OBJECT IDENTIFIER tag
// appears INSIDE the outer CONTEXT tag, not replaced by it) -- confirmed by hand against real
// captures; this decoder surfaces each present one as a plain OID/integer value without
// resolving AP-title-form1 (a full ASO-qualifier-and-AP-title-list structure, never observed in
// this decoder's own research) any further than "present, structurally skipped."
//
// ---------------------------------------------------------------------------------------------
// MMS layer (ISO 9506-2): the payload this entire file exists to reach. MMSpdu is a CHOICE of
// 14 alternatives, each its own CONTEXT-class constructed tag 0-13 (0xA0-0xAD):
//   0 confirmed-RequestPDU   1 confirmed-ResponsePDU  2 confirmed-ErrorPDU  3 unconfirmed-PDU
//   4 rejectPDU              5 cancel-RequestPDU      6 cancel-ResponsePDU  7 cancel-ErrorPDU
//   8 initiate-RequestPDU    9 initiate-ResponsePDU  10 initiate-ErrorPDU  11 conclude-RequestPDU
//  12 conclude-ResponsePDU  13 conclude-ErrorPDU
//
// initiate-RequestPDU/ResponsePDU -- the MMS analog of this codebase's own S7comm "Setup
// Communication" / OPC UA OpenSecureChannel -- are decoded in FULL: localDetail(Calling/Called),
// proposedMaxServOutstanding(Calling/Called), proposed/negotiatedDataStructureNestingLevel, and
// the nested InitRequestDetail/InitResponseDetail's own version number and two BIT STRING
// capability fields (ParameterSupportOptions -- str1/str2/vnam/valt/vadr/vsca/tpy/vlis/real/cei
// -- and ServiceSupportOptions, one bit per confirmed service, ~85 bits) -- this decoder
// surfaces every SET bit by name for both, the same "decode the whole capability negotiation,
// it's small and always present" posture OPC UA's OpenSecureChannel gets in this codebase.
//
// confirmed-RequestPDU/ResponsePDU always carry an invokeID (an application-chosen correlation
// number, this decoder's OWN closest analog to OPC UA's RequestHandle/S7comm's PDU reference --
// but see "Deliberately NOT implemented", this decoder does not correlate a response back to
// its own request across packets) and a ConfirmedServiceRequest/Response CHOICE selecting one
// of 78 defined confirmed services (status, getNameList, identify, rename, read, write,
// getVariableAccessAttributes, defineNamedVariable, ... down to fileDirectory) -- this decoder's
// own dispatch table names every one of the 78 (so an unrecognized numeric tag never happens
// for a spec-conformant confirmed service) and splits them into two tiers exactly as this
// codebase already does for OPC UA's own service dispatch:
//
// Tier 1 (full field decode): status, getNameList, identify, read, write,
// getVariableAccessAttributes, defineNamedVariableList, getNamedVariableListAttributes,
// deleteNamedVariableList, getCapabilityList, getDomainAttributes -- the services this
// decoder's own research found are (a) universally present in real IEC 61850 MMS traffic (model
// browsing via getNameList, the actual reads/writes of process data via read/write, session
// capability negotiation) and (b) simple enough to decode with full confidence. Tier 1 also
// covers unconfirmed-PDU's own informationReport (the MMS analog of this codebase's own GOOSE
// decoder -- see "InformationReport" below) and every one of rejectPDU/cancel-*/conclude-*
// (each small and fully specified).
//
// Tier 2 (service name + invokeID only, body shown as raw hex): every other confirmed service
// (rename, defineNamedVariable, defineScatteredAccess, getScatteredAccessAttributes,
// deleteVariableAccess, defineNamedType, getNamedTypeAttributes, deleteNamedType, input, output,
// takeControl, relinquishControl, every semaphore/event-condition/event-action/
// event-enrollment/journal/file/program-invocation/domain-download service) -- these are, in
// this decoder's own research, genuinely rare in ordinary IEC 61850 process-data traffic
// (belonging more to MMS's original general-purpose industrial-messaging scope than to IEC
// 61850's own narrower profile of it) and each has its own, sometimes large, request/response
// grammar this first-pass release does not implement field-by-field.
//
// The Data value type: UNLIKE this codebase's own OPC UA decoder (which deliberately leaves
// Variant/DataValue -- OPC UA's own self-describing value encoding -- undecoded, see
// opcua.hpp), this decoder DOES fully implement MMS's own "Data" CHOICE (ISO 9506-2's own
// self-describing value type, used everywhere an actual read/write/report VALUE appears on the
// wire): array/structure (recursive SEQUENCE OF Data, tags 1/2 -- see "Recursion depth cap"
// below), boolean(3), bit-string(4), integer(5)/unsigned(6) (BER INTEGER, sign-extended for
// integer, not for unsigned), floating-point(7) (see "FloatingPoint encoding" below),
// octet-string(9), visible-string(10), binary-time(12), bcd(13), booleanArray(14) (a BIT STRING
// whose bits are individually rendered true/false), objId(15) (an OBJECT IDENTIFIER), mMSString
// (16, a UTF-8 string -- an IEC 61850 Edition 2 addition), utc-time(17) (an IEC 61850-8-1
// addition -- see "UtcTime encoding" below). This is a genuine, meaningful strength of this
// decoder over leaving values opaque: the actual point values an MMS client reads or writes,
// and every value inside an InformationReport, ARE visible in this decoder's own output, not
// merely that a read/write/report happened.
//
// FloatingPoint encoding (used for every IEC 61850 analog measurement -- MX-class data like
// AnIn/TotW/Hz): NOT a plain IEEE754 float. The wire value is an OCTET STRING whose first byte
// is the exponent width in BITS (8 for IEEE754 single-precision, the only width this decoder's
// own research ever found in practice) followed by the IEEE754 value itself, big-endian --
// confirmed byte-for-byte against real independent-stack-generated traffic (see
// ATTRIBUTION.md). A FloatingPoint whose declared exponent width is not 8 (a legal, if
// vanishingly rare in IEC 61850 practice, encoding this decoder's own research never found) is
// shown as raw hex rather than guessed at.
//
// UtcTime encoding (IEC 61850-8-1's own addition, used for MX/ST-class timestamps): an 8-byte
// OCTET STRING -- 4 bytes SecondsSinceEpoch (UInt32, seconds since 1970-01-01T00:00:00Z) + 3
// bytes FractionOfSecond (a 24-bit fixed-point fraction) + 1 byte flags (bit 0x80
// leap-seconds-known, 0x40 clock-failure, 0x20 clock-not-synchronized, low 5 bits time accuracy
// in bits) -- this decoder renders the calendar timestamp plus the flag bits by name, the same
// depth this codebase's own GOOSE/SV decoders already give their own timestamp fields.
//
// Recursion depth cap: Data's own array/structure alternatives are recursive (a SEQUENCE OF
// Data, each element potentially itself an array/structure). This decoder caps recursion depth
// defensively -- a real, independently-reproducible bug was found DURING this decoder's own
// validation: `tshark` 4.2.2's own MMS dissector hits an internal recursion-depth assertion and
// gives up entirely on some genuine, non-malicious, independent-stack-generated report traffic
// this decoder's own research captured (see ATTRIBUTION.md) -- a concrete, observed reminder
// that an attacker-controlled or merely malformed deeply-nested Data value is a real
// denial-of-service surface for any MMS parser that recurses unboundedly, this decoder included
// were it not for this cap. Past the cap, this decoder stops descending and shows the remaining
// bytes as raw hex rather than recursing further or guessing -- never crashing, never hanging.
//
// InformationReport (unconfirmed-PDU's own [0] alternative -- the MMS analog of this codebase's
// own GOOSE decoder, and IEC 61850-8-1's actual mechanism for Buffered/Unbuffered Report Control
// Blocks): decoded in full -- variableAccessSpecification (either a listOfVariable, each entry
// an ObjectName rendered the same domain/item "$"-separated-path style as GetNameList/Read/
// Write below, or a variableListName ObjectName, including the special, reserved
// vmd-specific "RPT" name this decoder's own research found real Report traffic actually uses
// to mean "this report's own pre-configured dataset" rather than naming an explicit variable
// list) and listOfAccessResult (each entry decoded with the same Data-value decoder used
// everywhere else in this file). This decoder does NOT attempt to label which positional value
// in that list is RptID vs. SeqNum vs. an actual dataset member's value -- IEC 61850's own
// optional-fields negotiation (ReportedOptFlds, decided out-of-band when the Report Control
// Block was configured, not carried on every report) determines that, information this
// stateless-per-message decoder does not have -- the SAME honest positional-list-without-field-
// labels posture this codebase's own GOOSE decoder already takes for allData, applied here to
// MMS Reports for the identical reason.
//
// ObjectName rendering: domain-specific (the overwhelmingly common IEC 61850 shape) is rendered
// "domainId/itemId" (e.g. "simpleIOGenericIO/GGIO1$MX$AnIn1$mag$f" -- the itemId's own "$"
// separators are IEC 61850's own convention for a logical-node/functional-constraint/data-
// object/data-attribute path, left as-is rather than reinterpreted, the same "show the wire
// string, don't guess at SCL-level semantics this decoder has no access to" posture this
// codebase's own GOOSE decoder already takes for gocbRef/datSet); vmd-specific and aa-specific
// are rendered as their own bare Identifier string.
//
// ServiceError (confirmed-ErrorPDU, cancel-ErrorPDU, conclude-ErrorPDU, initiate-ErrorPDU):
// decoded into an errorClass category name + numeric code (e.g. "access(2)" for
// object-non-existent) plus, when present, additionalCode and additionalDescription -- the MMS
// analog of this codebase's own S7comm error-class/error-code or OPC UA StatusCode decode.
// rejectPDU is decoded into its own originalInvokeID (when present) and rejectReason category +
// specific reason name.
//
// ---------------------------------------------------------------------------------------------
// Deliberately NOT implemented: stateful association/invocation tracking (correlating a later
// Data-Transfer message's presentation-context-id back to an earlier Connect frame's own
// context-definition-list -- see "Resolving which context-id means ACSE vs. MMS" above --  or a
// confirmed-ResponsePDU's own invokeID back to the confirmed-RequestPDU that invoked it) --
// this decoder is, like every other protocol in this codebase, a stateless-per-message decoder
// with TCP-stream-level reassembly only (COTP's own EOT-based fragment reassembly, already
// implemented in cotp.hpp/decoder.cpp and shared with S7comm -- MMS does not need its own);
// Presentation-layer context renegotiation mid-association (ISO 8823's own
// "presentation-context-addition-list" extension) -- never observed in this decoder's own
// research; AARQ/AARE's own authentication-value field (ACSE's optional password/certificate
// authentication mechanism) is structurally skipped, not decoded -- never observed in this
// decoder's own research, and, per ACSE's own EXPLICIT tagging (see above), safely skippable
// without losing byte alignment for whatever follows; and MMS's own file-transfer services
// (obtainFile/fileOpen/fileRead/fileClose/fileRename/fileDelete/fileDirectory) are named
// (Tier 2) but not decoded -- IEC 61850's own COMTRADE/disturbance-file-retrieval use of MMS
// file services is a real, if narrower, OT-security-relevant use case this first-pass release
// leaves for future work (see ROADMAP in docs/MANUAL.md).
//
// Validation: see this file's own real-capture search record in tests/real_captures/mms/
// ATTRIBUTION.md for the current state of that search, including both genuine real-world
// captures and this decoder's own independent-stack-generated validation traffic.
#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include "conduitscope/byteio.hpp"

namespace conduitscope {

// One decoded MMS frame -- everything this decoder reached across all four layers (Session/
// Presentation/ACSE/MMS) for one COTP Data frame's own user data. See mms.hpp's file header
// comment for the full byte layout and decode scope of every field below.
struct MmsFrame {
    // ---- Session layer -- always populated when this decoder recognized the frame at all,
    // UNLESS this is a "bare" MMS frame (see mms_is_bare below), in which case every
    // session_*/presentation_*/acse_* field below is left at its default.
    bool is_bare = false;  // true: no Session/Presentation/ACSE at all, MMS PDU starts the frame
    uint8_t session_spdu_type = 0;
    std::string session_pdu_name;  // "CONNECT (CN)", "DATA TRANSFER / GIVE TOKENS", ...

    // ---- Presentation layer -- populated whenever Session's own user-data parameter was
    // present and this decoder could unwrap it as fully-encoded-data (the only alternative
    // implemented -- see file header comment).
    bool has_presentation = false;
    // Association-time only (a Session CONNECT/ACCEPT carrying a CP-type/CPA-type with its own
    // presentation-context-definition-list) -- each entry "context N = <name> (<OID>)".
    std::vector<std::string> presentation_context_list;
    uint32_t presentation_context_id = 0;  // the PDV's own presentation-context-identifier
    bool presentation_context_is_acse = false;  // per the 1=ACSE/3=MMS convention -- see file header

    // ---- ACSE layer -- populated only on an association-establishment/release frame.
    bool has_acse = false;
    std::string acse_pdu_name;  // "AARQ"/"AARE"/"RLRQ"/"RLRE"/"ABRT"
    std::string acse_application_context_name;  // "1.0.9506.2.3 (MMS)" when recognized
    bool acse_has_result = false;               // AARE only
    std::string acse_result_name;               // "accepted"/"rejected-permanent"/"rejected-transient"
    std::vector<std::string> acse_values;  // AP-title/AE-qualifier/diagnostic detail, "key=value"

    // ---- MMS layer -- the actual payload. Populated whenever this decoder reached a
    // recognized MMSpdu CHOICE tag, whether by unwrapping ACSE's own user-information (an
    // association frame) or Presentation's MMS-context PDV directly (an ongoing Data-Transfer
    // frame) or a bare frame (mms_is_bare).
    bool has_pdu = false;
    std::string pdu_name;  // "initiate-RequestPDU", "confirmed-RequestPDU", "unconfirmed-PDU", ...

    bool has_invoke_id = false;  // confirmed-Request/Response/ErrorPDU only
    uint32_t invoke_id = 0;

    bool service_recognized = false;  // the ConfirmedService(Request|Response) CHOICE tag was named
    std::string service_name;         // e.g. "read", "getNameList" -- empty when !service_recognized
    bool service_body_decoded = false;  // true for Tier 1 (full decode); false for Tier 2/unrecognized

    bool is_response = false;  // best-effort: true for a *ResponsePDU shape, false for *RequestPDU

    bool has_error = false;  // confirmed-ErrorPDU/initiate-ErrorPDU/cancel-ErrorPDU/conclude-ErrorPDU
    std::string error_name;  // "access(2)" style category(code), plus additionalCode/Description in notes

    // Tier 1 service-specific decoded fields (and Initiate's own capability negotiation, and
    // InformationReport's own variable+value list, and ServiceError/RejectPDU detail), "key=value"
    // each -- mirrors opcua_values'/hartip_values' scheme.
    std::vector<std::string> values;

    bool body_shown_as_hex = false;
    std::string body_hex;
    size_t body_length = 0;

    std::string summary;
    std::vector<std::string> notes;
};

// Attempts to interpret `cotp_user_data` (the payload of a COTP Data frame, AFTER try_parse_s7comm
// has already been tried and returned std::nullopt -- S7comm's own single-byte protocol-id gate is
// tried first, unconditionally, since it is a materially stronger and cheaper check -- see
// decoder.cpp's own dispatch-order comment) as an IEC 61850 MMS frame (Session/Presentation/ACSE/
// MMS, or a bare MMS PDU -- see file header comment). Returns std::nullopt (never throws) when the
// leading byte matches neither a recognized Session SPDU type nor a bare MMS PDU tag -- the
// standard signal that this COTP Data frame is carrying something else entirely. Once that
// structural gate passes, a header/TLV that is too short or internally inconsistent for what it
// claims throws ParseError rather than silently returning a partial result, the same posture
// every other parser in this codebase takes.
std::optional<MmsFrame> try_parse_mms(ByteSpan cotp_user_data);

}  // namespace conduitscope
